### ISSUE TITLE
[BUG] Error DATAPUSHER with CKAN__ROOT_PATH variable

### ISSUE THREAD

**Issue by eduynza** [keitaroinc/docker-ckan#66]
**Describe the bug**
Hi, everyone.
When I declare the variable **CKAN__ROOT_PATH**, the **DATAPUSHER** extension stopped working.

According to the documetation in [https://docs.ckan.org/en/2.9/maintaining/configuration.html#ckan-root-path](https://docs.ckan.org/en/2.9/maintaining/configuration.html#ckan-root-path) must be change this variables in **who.ini**: **login_form_url**, **post_login_url** and **post_logout_url**

I also added a **nginx** container

**Docker images affected**
CKAN 2.9.0 (No verified)
CKAN 2.9.2
CKAN 2.9.3
CKAN 2.9.4
CKAN 2.9.5

**How to reproduce the error**
- .ckan-env
```
# General Settings
CKAN_SITE_URL=http://localhost
#CKAN_PORT=80
CKAN_MAX_UPLOAD_SIZE_MB=100
CKAN__ROOT_PATH=/repo/{{LANG}}
....other-instructions....

# Datapusher configuration
CKAN__DATAPUSHER__URL=http://datapusher:8000
CKAN__DATAPUSHER__CALLBACK_URL_BASE=http://ckan:5000/
```
- .env
```
# CKAN
CKAN_SITE_URL=http://localhost
#CKAN_PORT=80
CKAN_MAX_UPLOAD_SIZE_MB=100
....other-instructions....

# Datapusher
DATAPUSHER_VERSION=0.0.17
DATAPUSHER_MAX_CONTENT_LENGTH=10485760
DATAPUSHER_CHUNK_SIZE=16384
DATAPUSHER_CHUNK_INSERT_ROWS=250
DATAPUSHER_DOWNLOAD_TIMEOUT=30
DATAPUSHER_SSL_VERIFY=False
DATAPUSHER_REWRITE_RESOURCES=True
DATAPUSHER_REWRITE_URL=http://ckan:5000
```
- docker-compose.yml
```
....other-instructions....
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    networks:
      - frontend
      - backend
    depends_on:
      - ckan
      - datapusher
    ports:
      - "0.0.0.0:80:80"

  ckan:
    container_name: ckan
    image: ghcr.io/keitaroinc/ckan:${CKAN_VERSION}
    networks:
      - frontend
      - backend
    depends_on:
      - db
    env_file:
      - ./.ckan-env
    environment:
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@db/datastore
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_SITE_URL=${CKAN_SITE_URL}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
    volumes:
      - ckan_data:/srv/app/data

  datapusher:
    container_name: datapusher
    image: ghcr.io/keitaroinc/datapusher:${DATAPUSHER_VERSION}
    networks:
      - frontend
      - backend
    environment:
      - DATAPUSHER_MAX_CONTENT_LENGTH=${DATAPUSHER_MAX_CONTENT_LENGTH}
      - DATAPUSHER_CHUNK_SIZE=${DATAPUSHER_CHUNK_SIZE}
      - DATAPUSHER_CHUNK_INSERT_ROWS=${DATAPUSHER_CHUNK_INSERT_ROWS}
      - DATAPUSHER_DOWNLOAD_TIMEOUT=${DATAPUSHER_DOWNLOAD_TIMEOUT}
      - DATAPUSHER_SSL_VERIFY=${DATAPUSHER_SSL_VERIFY}
      - DATAPUSHER_REWRITE_RESOURCES=${DATAPUSHER_REWRITE_RESOURCES}
      - DATAPUSHER_REWRITE_URL=${DATAPUSHER_REWRITE_URL}
....other-instructions....
```
- who.ini
```
....other-instructions....
[plugin:friendlyform]
use = ckan.lib.repoze_plugins.friendly_form:FriendlyFormPlugin
login_form_url= /repo/user/login
login_handler_path = /login_generic
logout_handler_path = /user/logout
rememberer_name = auth_tkt
post_login_url = /repo/user/logged_in
post_logout_url = /repo/user/logged_out
....other-instructions....
```
- nginx (new container)
```
nginx
├─setup
│  ├─sites-available
│  │  └─ckan.conf
│  └─nginx.conf
├─Dockerfile
└─index.html
```
```
------------- Dockerfile -------------- 
FROM nginx:alpine

ENV NGINX_DIR=/etc/nginx

COPY ./nginx/index.html /usr/share/nginx/html/index.html
RUN mkdir -p ${NGINX_DIR}/sites-available
RUN mkdir -p ${NGINX_DIR}/sites-enabled

COPY ./nginx/setup/nginx.conf ${NGINX_DIR}
COPY ./nginx/setup/sites-available/* ${NGINX_DIR}/sites-available
RUN ln -s ${NGINX_DIR}/sites-available/ckan.conf ${NGINX_DIR}/sites-enabled/ckan.conf

EXPOSE 80
---------------------------------------

-------------- nginx.conf -------------
user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    #tcp_nopush     on;
    keepalive_timeout  65;
    #gzip  on;
    include /etc/nginx/sites-enabled/*.conf;
}
--------------------------------------

-------------- ckan.conf -------------
proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=cache:30m max_size=250m;
proxy_temp_path /tmp/nginx_proxy 1 2;

server {
    client_max_body_size 100M;
    location /repo {
        proxy_pass http://ckan:5000/;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_cache cache;
        proxy_cache_bypass $cookie_auth_tkt;
        proxy_no_cache $cookie_auth_tkt;
        proxy_cache_valid 30m;
        proxy_cache_key $host$scheme$proxy_host$request_uri;
        # In emergency comment out line to force caching
        # proxy_ignore_headers X-Accel-Expires Expires Cache-Control;
    }
}
--------------------------------------
```
**Expected behaviour**
All operations successfully completed - Datapusher.

**Logs**

- terminal
![Captura de pantalla de 2022-01-24 14-17-49](https://user-images.githubusercontent.com/63824219/150849528-99370596-53b5-40c4-94b3-62ecff245087.png)
- website
![Captura de pantalla de 2022-01-24 14-20-33](https://user-images.githubusercontent.com/63824219/150849965-9a887f1f-dfc4-4ef7-ad7a-d9393d0ec8c6.png)
